---
title: "gl-anova"
output: html_document
date: "2023-10-23"
---


```{r}
library('tidyverse')
library('ggpubr')
library('rstatix')
library('ARTool')
library('rcompanion')
library('effectsize')
library('ggplot2')
```


```{r}
data_frame <- read.csv("C:/Users/Vit/Desktop/gl-paper/green-ml-anonymized/new_analysis/new_rq1_rq3/rq1-data.csv")

head(data_frame)
```

```{r}
data_frame <- subset(data_frame, id != 616)

data_frame %>%
  group_by(dataset) %>%
  get_summary_stats(joules, type = "full")
```

```{r}
# boxplot without outliers
ggplot(data_frame, aes(x = joules, y = dataset)) +
  #geom_boxplot() +
  geom_boxplot(outlier.shape = NA, outlier.colour = NA) +
  theme_minimal() +
  coord_cartesian(xlim = c(0, 1500)) +
  labs(title = "Energy consumption in all experiments", x = "energy consumption in joules", y = "") # +
```

```{r}
data_frame %>%
  group_by(dataset) %>%
  identify_outliers(joules)

df_outliers <- data_frame %>% 
  group_by(dataset) %>% 
  identify_outliers(joules)

data_frame <- data_frame %>% 
  anti_join(df_outliers, by = "id")
```

```{r}
kruskal.test(joules ~ dataset, data = data_frame)
```


