---
title: "gl-anova"
output: html_document
date: "2023-10-23"
---


```{r}
library('tidyverse')
library('ggpubr')
library('rstatix')
library('ARTool')
library('rcompanion')
library('effectsize')
library('ggplot2')
```


```{r}
data_frame <- read.csv("C:/Users/Vit/Desktop/gl-paper/green-ml-anonymized/new_analysis/new_rq1_rq3/rq3-data.csv")

head(data_frame)
```

```{r}
data_frame %>%
  group_by(dataset, features) %>%
  get_summary_stats(joules, type = "full")
```

```{r}
data_frame %>%
  group_by(dataset, features) %>%
  identify_outliers(joules)

df_outliers <- data_frame %>% 
  group_by(dataset, features) %>% 
  identify_outliers(joules)

data_frame <- data_frame %>% 
  anti_join(df_outliers, by = "id")
```

```{r}
data_frame$features <- factor(data_frame$features)
data_frame$algorithm <- factor(data_frame$algorithm)
data_frame$dataset <- factor(data_frame$dataset)

# repeated measures:
#model_energy_usage <- art(joules ~ Error(exp/(algorithm * features) + dataset), data = data_frame)

# simpler case:
model_energy_usage <- art(joules ~ dataset*features, data = data_frame)
anova(art(joules ~ dataset*features, data = data_frame))
art.con(model_energy_usage, "dataset")
art.con(model_energy_usage, "features")
art.con(model_energy_usage, "dataset:features", adjust = "none")
```

```{r}
# box plot

# Example data
# D <- data.frame(
#   i = factor(rep(1:5, each = 20)), # subject identifiers
#   j = rnorm(100) # values of interest
# )

ggplot(D, aes(x = i, y = j)) +
  geom_boxplot() +
  labs(title = "Boxplot of j for each subject", x = "Subject", y = "Values of j")

#alternative plot graphics
#boxplot(j ~ i, data = D, main = "Boxplot of j for each subject", xlab = "Subject", ylab = "Values of j")

```

